owner: bradp
repo: uptime
user-agent: bradp
assignees:
  - bradp

sites:
  - name: bradparbs.com
    url: https://bradparbs.com
    icon: https://bradparbs.com/images/icons/favicon-32x32.png
  - name: brad.party (redirect)
    url: https://brad.party
  - name: parbs.org (redirect)
    url: https://parbs.org
  - name: parbs.me (redirect)
    url: https://parbs.me
  - name: parbs.co (redirect)
    url: https://parbs.co
  - name: brad.cash
    url: https://brad.cash
    icon: https://brad.cash/favicon-32x32.png
  - name: brrad.com (redirect)
    url: https://brrad.com
  - name: brrad.com/w
    url: https://brrad.com/w
  - name: status.brrad.com
    url: https://status.brrad.com
  - name: sax.cat
    url: https://sax.cat
    icon: https://sax.cat/favicon-32x32.png
  - name: mouse.rip
    url: https://mouse.rip
    icon: https://mouse.rip/favicon.ico
  - name: api.mouse.rip
    url: https://mouse.rip/favicon.ico
  - name: guide.mouse.rip
    url: https://guide.mouse.rip
  - name: guide-preview.mouse.rip
    url: https://guide-preview.mouse.rip
  - name: items.mouse.rip
    url: https://items.mouse.rip
  - name: mousehunt.org (redirect)
    url: https://mousehunt.org

status-website:
  cname: status.brrad.com
  logoUrl: https://brrad.com/tada.png
  name: "Brad Parbs Uptime"
  introTitle: ""
  introMessage: ""
  navbar:
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
