owner: bradp
repo: uptime

sites:
  - name: BradParbs.com
    url: https://bradparbs.com
  - name: brrad.com
    url: https://brrad.com/w
  - name: Is it snowing in MKE?
    url: https://isitsnowinginmilwaukee.com
  - name: gifsb.in
    url: https://gifsb.in
  - name: sax.cat
    url: https://sax.cat
  - name: butts.tech
    url: https://butts.tech
  - name: 10upsidedown.com
    url: https://10upsidedown.com
  - name: fauxio
    url: https://faux.io
  - name: brad.cash
    url: https://brad.cash

status-website:
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime
  introTitle: "Uptime - powered by GitHub."
  introMessage: "Status page for my sites (@bradp)"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

assignees:
  - bradp

user-agent: bradp
